chi_traffic_crash:
  outputs:
    dev:
      dataset: chi_traffic
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: chi-traffic-gcp
      threads: 1
      type: bigquery
  target: dev
