steps:
  - name: python
    entrypoint: pip
    args: ["-c", "cd airflow && pip install -r utils/requirements.txt --user"]

  - name: python
    entrypoint: python
    args: ["-c", "cd airflow && python utils/add_dags_to_composer.py --dags_directory=${_DAGS_DIRECTORY} --dags_bucket=${_DAGS_BUCKET}"]

options:
  logging: CLOUD_LOGGING_ONLY
