steps:
  - name: python
    entrypoint: pip
    args: ["install", "-r", "utils/requirements.txt", "--user" ]

  - name: python
    entrypoint: python
    args: ["utils/add_dags_to_composer.py", "--dags_directory=${_DAGS_DIRECTORY}", "--dags_bucket=${_DAGS_BUCKET}"]
