steps:
  # install dependencies
  - name: python:3.11-slim
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "-c", "constraints.txt", "--user"]

  - name: python:3.11-slim
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  - name: python:3.11-slim
    entrypoint: python3.11
    args: ["-m", "pytest", "-s", "dags/"]

options:
  logging: CLOUD_LOGGING_ONLY
